name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : Configure git username and email...
      run : git config user.name github-actions && git config user.email github-actions@github.com
      shell: bash
    - name : Install dependencies...
      run : npm i -f
      shell: bash
    - name : Build react app...
      run : CI=false npm run build
      shell: bash
    - name : Add changes from the working tree...
      run : git --work-tree build add --all
      shell: bash
    - name : Committ changes...
      run : git commit -m "Automatically deploying v$(npm version | grep 'site' | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+[^']*")"
      shell: bash
    - name : Push changes to gh-pages branch...
      run : git push origin HEAD:gh-pages --force
      shell: bash
