name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : Configure git username and email...
      run : git config user.name emyron96 && git config user.email emyron96@gmail.com
      shell: bash
    - name : Install dependencies...
      run : npm i -f
      shell: bash
    - name : Build react app...
      run : CI=false npm run deploy
      shell: bash
